---
Name: innoweb-requirements-resolver
---
Innoweb\RequirementsResolver\RequirementsResolver:
  requirements:
    jquery: '//cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js'
    'jquery-validate': '//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js'
    'jqueryui-js': '//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js'

SilverStripe\Core\Injector\Injector:
  SilverStripe\View\Requirements_Backend:
    class: Innoweb\RequirementsResolver\PrioritisingJavascriptRequirementsBackend