---
Name: innoweb-requirements-resolver
---
Innoweb\RequirementsResolver\RequirementsResolver:
  requirements:
    jquery: '//code.jquery.com/jquery-3.3.1.min.js'
    'jquery-validate': '//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js'
    'jqueryui-js': '//code.jquery.com/ui/1.12.1/jquery-ui.min.js'

SilverStripe\Core\Injector\Injector:
  SilverStripe\View\Requirements_Backend:
    class: Innoweb\RequirementsResolver\PrioritisingJavascriptRequirementsBackend